Auto gradiant calc:

Uses Autograd package

In [3]:
import torch

x= torch.randn(3, requires_grad= True)
print (x)

y= x+2
print(y) #AddBackward0
z =y*y*2 #MulBackward
#z=z.mean() #MeanBackward
print(z)
v = torch.tensor([.01,1.0,0.001], dtype=torch.float32)
z.backward(v) #dz/dx
print(x.grad)

tensor([-1.4505,  0.2830, -1.3287], requires_grad=True)
tensor([0.5495, 2.2830, 0.6713], grad_fn=<AddBackward0>)
tensor([ 0.6039, 10.4241,  0.9014], grad_fn=<MulBackward0>)
tensor([2.1981e-02, 9.1320e+00, 2.6853e-03])


Preventing Grad history:

In [ ]:
import torch

x= torch.randn(3, requires_grad= True)
print (x)

# methods used to prevent grad history:
#x.requires_grad_(False)
#x.detach()
#with torch.no_grad()

x.requires_grad_(False) #x.requires_grad_(False) method

print(x)

y= x.detach() #x.detach() method

print(y)

with torch.no_grad(): #with torch.no_grad() method
    y = x 
    print (y)




tensor([-1.1459, -0.7533, -1.1162], requires_grad=True)
tensor([-1.1459, -0.7533, -1.1162])
tensor([-1.1459, -0.7533, -1.1162])
tensor([-1.1459, -0.7533, -1.1162])


Dummy training example:

In [22]:
import torch

weights = torch.ones(4, requires_grad= True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


Optimization example : 

In [ ]:
import torch

weights = torch.ones(4, requires_grad= True)

optimizer =torch.optim.SGD(weights, lr=0.01)

optimizer.step()
optimizer.zero_grad()