In [54]:
!nvidia-smi


Mon Mar 10 14:25:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40S                    Off |   00000000:46:00.0 Off |                    0 |
| N/A   50C    P0            293W /  350W |   41059MiB /  46068MiB |     93%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Empty tensor :

In [65]:
import torch

x = torch.empty(2,3)

print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])


Random tensor:

In [66]:
import torch

x = torch.rand(2,2)

print(x)


tensor([[0.8003, 0.9744],
        [0.0733, 0.2368]])


tensor with Specific data type

In [68]:
import torch

x = torch.ones(2, dtype = torch.int)

print(x)


tensor([1, 1], dtype=torch.int32)


Tensor from data list


In [69]:
import torch

x = torch.tensor([2.5,0.1])

print(x)

tensor([2.5000, 0.1000])


Basic Operations 

In [102]:
import torch

x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)
z = x + y

print(z)

a = x - y
print(a)

b = x * y
print(b)

c = x / y
print(c)


tensor([[0.5904, 0.3311],
        [0.4684, 0.0976]])
tensor([[0.4925, 0.5939],
        [0.2907, 0.8047]])
tensor([[1.0828, 0.9250],
        [0.7591, 0.9022]])
tensor([[ 0.0979, -0.2628],
        [ 0.1777, -0.7071]])
tensor([[0.2907, 0.1966],
        [0.1362, 0.0785]])
tensor([[1.1988, 0.5576],
        [1.6111, 0.1212]])


inplace addition: 
"trailing_" will do an inplace operation i.e add_

In [76]:
import torch

x = torch.rand(2,2)
y = torch.rand(2,2)
y.add_(x)
print(y)

tensor([[0.9746, 0.4368],
        [1.1202, 0.8843]])


Slicing:

In [81]:
import torch

x = torch.rand(5,3)
print(x)
print(x[:, 0]) #all the rows and 0th coloum
print(x[1, :]) # all the coloum 1st row
print(x[1,1]) #one element in tensor
print(x[1,1].item()) #actual value


tensor([[0.5322, 0.3259, 0.5992],
        [0.3269, 0.1442, 0.6996],
        [0.6648, 0.6239, 0.8832],
        [0.5097, 0.2079, 0.9323],
        [0.1569, 0.7158, 0.3671]])
tensor([0.5322, 0.3269, 0.6648, 0.5097, 0.1569])
tensor([0.3269, 0.1442, 0.6996])
tensor(0.1442)
0.14419716596603394


Reshaping tensor:

In [ ]:
import torch

x = torch.rand(4,4)
print(x)

y = x.view(16)
print(y)

tensor([[0.5666, 0.0983, 0.7515, 0.0396],
        [0.2469, 0.5241, 0.2592, 0.7878],
        [0.3701, 0.3292, 0.2760, 0.3551],
        [0.2703, 0.4635, 0.0592, 0.1290]])
tensor([0.5666, 0.0983, 0.7515, 0.0396, 0.2469, 0.5241, 0.2592, 0.7878, 0.3701,
        0.3292, 0.2760, 0.3551, 0.2703, 0.4635, 0.0592, 0.1290])


numpy to torch tensor

In [86]:
import torch
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print (b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Numpy array initially

In [91]:
import torch
import numpy as np

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1 #increment
print (a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


tensor on gpu

In [98]:
import torch
import numpy as np

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y= y.to(device)
    z=x+y
    print(z)

tensor([2., 2., 2., 2., 2.], device='cuda:0')


Arg for specifying gradiants:

In [99]:
import torch
import numpy as np
x=torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
